config/routes.rb
MondernMustangs::Application.routes.draw do

  devise_for :admins

  resources :posts do
    resources :comments
  end

  mount Forem::Engine, :at => '/forums'

  devise_for :users

  root :to => "posts#index"
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :body, :title

  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # def to_s
  #   name
  # end
  
  # def email
  #   email_address
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def forem_user
    current_user
  end
  
  helper_method :forem_user

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to @post
  end

private
  def comment_params
    params.require(:comment).permit(:post_id, :body)
  end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  layout "blog"

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Comment.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
        format.atom 
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  

  def title(page_title)
    content_for :title, page_title.to_s
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <p><%= time_ago_in_words(comment.created_at) %></p>
  <p><%= h(comment.body) %></p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/forem/admin/categories/_form.html.erb
<%= simple_form_for [forem, :admin, @category] do |f| %>
  <%= f.input :name %>
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/forem/admin/categories/edit.html.erb
<h2><%= t("forem.admin.category.edit", :title => @category.name) %></h2>

<%= render "form" %>

app/views/forem/admin/categories/index.html.erb
<h2><%= t("forem.admin.category.index") %></h2>
<%= link_to t('back_to_admin', :scope => "forem.admin"), forem.admin_root_path %><br><br>
<%= link_to t("forem.admin.category.new_link"), forem.new_admin_category_path, :class => "btn btn-primary" %><br><br>

<table id='forums' class='forums table-striped table' cellspacing='0'>
  <thead>
    <tr>
      <th><%= t('edit', :scope => 'forem.admin.categories') %></th>
      <th><%= t('delete', :scope => 'forem.admin.categories') %></th>
      <th><%= t('category', :scope => 'forem.admin.categories') %></th>

    </tr>
  </thead>
  <tbody>
    <% @category.each do |category| %>
      <tr class="forum <%= cycle("odd", "even") %>">
        <td><%= link_to t('edit', :scope => 'forem.admin.categories'), forem.edit_admin_category_path(category), :class => "btn btn-info" %></td>
        <td><%= link_to t('delete', :scope => 'forem.admin.categories'), forem.admin_category_path(category), :method => :delete, 
        data: { :confirm => t("delete_confirm") }, :class => "btn btn-danger" %></td>
        <td>
          <%= forem_emojify(category.name) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('forem.admin.forum.index'), forem.admin_forums_path %>

app/views/forem/admin/categories/new.html.erb
<h2><%= t('new', :scope => 'forem.admin.category') %></h2>

<%= render "form" %>

app/views/forem/admin/forums/_form.html.erb
<%= simple_form_for [forem, :admin, @forum] do |f| %>
  <%= f.association :category, :include_blank => false %>
  <%= f.input :title %>
  <%= f.input :description, :as => :text %>

  <h3><%= t('forem.admin.forum.moderator_groups') %></h3>
  <%= f.association :moderators, :as => :check_boxes %>
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/forem/admin/forums/edit.html.erb
  <h2><%= t("forem.forum.edit", :title => forem_emojify(@forum.title)).html_safe %></h2>

  <%= render "form" %>

app/views/forem/admin/forums/index.html.erb
<div>
  <h2><%= t("forem.admin.forum.index") %></h2>
  <%= link_to t('back_to_admin', :scope => "forem.admin"), forem.admin_root_path %><br><br>
  <%= link_to t("forem.admin.forum.new_link"), forem.new_admin_forum_path, :class => "btn btn-primary" %>

  <% @forums.group_by(&:category).each do |category, forums| %>
    <h2><%= category.try(:name) || t('.no_category') %></h2>

    <table id='forums' class='forums table table-striped' cellspacing='0'>
      <thead>
        <tr>
          <th><%= t('edit', :scope => 'forem.admin.forums') %></th>
          <th><%= t('delete', :scope => 'forem.admin.forums') %></th>
          <th><%= t('forum', :scope => 'forem.general') %></th>
          <th><%= t('topics', :scope => 'forem.general') %></th>
          <th><%= t('posts', :scope => 'forem.general') %></th>
        </tr>
      </thead>
      <tbody>
        <% forums.each do |forum| %>
          <tr class="forum <%= cycle("odd", "even") %>">
            <td><%= link_to t('edit', :scope => 'forem.admin.forums'), forem.edit_admin_forum_path(forum), :class => "btn btn-info" %></td>
            <td><%= link_to t('delete', :scope => 'forem.admin.forums'), forem.admin_forum_path(forum), :method => :delete, data: { :confirm => t("delete_confirm") } , :scope => "forem.admin.forums", :class => "btn btn-danger" %></td>
            <td>
              <%= link_to forem_emojify(forum.title), forem.forum_path(forum) %>
              <div class='description'><%= forem_format(forum.description) %></div>
              <%= t('.last_post') %>
              <% if last_post = forum.posts.last %>
  <%= link_to(forem_emojify(last_post.topic.subject), forem.forum_topic_path(forum, last_post.topic)) -%> <%= t('by') %> <%= last_post.user %> <%= time_ago_in_words(last_post.created_at) -%>
              <% else %>
                <%= t('.none') %>
              <% end %>
              <br>
              <span class='moderators'>
                <strong><%= t('.moderators') %>:</strong>
                <% if forum.moderators.exists? %>
                  <% forum.moderators.map do |moderator| %>
                    <%= link_to moderator, [forem, :admin, moderator] %>
                  <% end.to_sentence %>
                <% else %>
                  None
                <% end %>
              </span>
            </td>
            <td><%= forum.topics.count %></td>
            <td><%= forum.posts.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/forem/admin/forums/new.html.erb
<h2><%= t("forem.forum.new") %></h2>

<%= render "form" %>

app/views/forem/admin/topics/_form.html.erb
<%= simple_form_for [forem, :admin, @topic] do |f| %>
  <%= f.input :subject %>
  <%= f.association :forum , :label => "Forum" %>
  <%= f.label :locked %>
  <%= f.check_box :locked %>
  <%= f.label :pinned %>
  <%= f.check_box :pinned %>
  <%= f.label :hidden %>
  <%= f.check_box :hidden %>

  <br />
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/forem/admin/topics/edit.html.erb
<h2><%= t("forem.topic.edit", :subject => @topic.subject) %></h2>

<%= render "form" %>

app/views/forem/categories/_category.html.erb
<% if can?(:read, category) %>
  <div id='category_<%= category.id %>' class='category'>
    <h2><%= link_to forem_emojify(category.name), [forem, category] %></h2>
    <%= render "/forem/forums/listing", :category => category %>
  </div>
<% end %>

app/views/forem/categories/show.html.erb
<div class='category'>
  <h2><%= link_to t('forem.forum.forums'), forem.forums_path %> &raquo; <%= link_to forem_emojify(@category), [forem, @category] %></h2>
  <%= render @category %>
</div>

app/views/forem/forums/_forum.html.erb
<% if can?(:read, forum) %>
  <tr class="forum <%= cycle("odd", "even") %>">
    <td>
      <%= link_to forem_emojify(forum.title), forem.forum_path(forum), :class => "title" %>
      <div class='description'><%= forem_format(forum.description) %></div>
      <%= t('forem.forums.index.last_post') -%>
      <span class='last_post'>
        <% if last_post = forum.last_post_for(forem_user) -%>
          <%= link_to(forem_emojify(last_post.topic.subject), forem.forum_topic_path(forum, last_post.topic)) -%> <%= t('by') %> <%= last_post.user %> 
          <time datetime="<%= last_post.created_at.to_s(:db) -%>"><%= "#{time_ago_in_words(last_post.created_at)} #{t("ago")}" %></time>
        <% else %>
          <%= t('forem.forums.index.none') -%>
        <% end %>
      </span>
    </td>
    <td class="topics-count"><%= topics_count(forum) %></td>
    <td class="posts-count"><%= posts_count(forum) %></td>
    <td class="views-count"><%= forum.views_count %></td>
  </tr>
<% end %>

app/views/forem/forums/_head.html.erb
<div id='forum'>
  <h2><%= link_to t('forem.forum.forums'), forem.root_path %> &raquo; <%= link_to forem_emojify(forum.category), [forem, forum.category] %> &raquo; <%= link_to forem_emojify(forum.title), [forem, forum] %></h2>
  <span id='description'><%= forem_format(forum.description) %></span>
  <div id='forum_topic_links' class='btn-group'>
    <% unless @topic.try(:new_record?) %>
      <% if can? :create_topic, @forum %>
        <%= link_to t('forem.topic.links.new'), forem.new_forum_topic_path(forum), :class => "btn btn-primary" %>
      <% end %>
    <% end %>
    <% if @topic %>
      <%= link_to t('forem.topic.links.back_to_topics'), forem.forum_path(forum), :class => "btn" %>
    <% end %>
    <% if can? :moderate, @forum %>
      <%= link_to t('forem.forum.moderator_tools'), forem.forum_moderator_tools_path(forum), :class => "btn btn-inverse" %>
    <% end %>
  </div>
</div>

app/views/forem/forums/_listing.html.erb
<table id='forums' class='forums table table-striped' cellspacing='0'>
  <thead>
  <tr>
    <th class="desc-and-last-post"><%= t('forum', :scope => 'forem.general') %></th>
    <th class="topics-count"><%= t('topics', :scope => 'forem.general') %></th>
    <th class="posts-count"><%= t('posts', :scope => 'forem.general') %></th>
    <th class="views-count"><%= t('forem.forums.index.views') %></th>
  </tr>
  </thead>
  <tbody>
    <%= render category.forums %>
  </tbody>
</table>

app/views/forem/forums/index.html.erb
<div id='forums_container'>
  <h1 id='forums_title'><%= t('.title') %></h1>

  <%= render @categories %>
</div>

<br>
<footer id='admin_link'>
  <% if forem_admin? %>
    <%= link_to t("area", :scope => "forem.admin"), forem.admin_root_path %>
  <% end %>
</footer>

app/views/forem/forums/show.html.erb
<div class='forum'>
  <%= render :partial => 'forem/forums/head', :locals => { :forum => @forum } %>

  <%= forem_pages_widget(@topics) %>
  <table class='topics table-striped table' cellspacing='0'>
    <thead>
      <tr>
        <th class="icon"></th>
        <th class="byline"><%= t('forem.topic.headings.topic') -%></th>
        <th class="latest-post"><%= t('forem.topic.headings.latest') -%></th>
        <th class="posts-count"><%= t('forem.topic.headings.posts') -%></th>
        <th class="views-count"><%= t('forem.topic.headings.views') -%></th>
      </tr>
    </thead>
    <tbody>
      <% if @topics.empty? %>
        <tr><td colspan='5' align='center'><%= t('forem.topic.none') %></td></tr>
      <% end %>
      <%= render @topics %>
    </tbody>
  </table>
  <%= forem_pages_widget(@topics) %>
</div>

app/views/forem/moderation/_options.html.erb
<p>
  <%= f.radio_button "moderation_option", "approve" %>
  <%= f.label "moderation_option_approve", t('approve', :scope => 'forem.posts.moderation'), :class => "label label-success" %>
</p>
<p>
  <%= f.radio_button "moderation_option", "spam" %>
  <%= f.label "moderation_option_spam", t('spam', :scope => 'forem.posts.moderation'), :class => "label label-important" %>
</p>
<br>
<%= f.submit t('moderate', :scope => 'forem.posts.moderation'), :class => "btn btn-primary" %>

app/views/forem/moderation/index.html.erb
<h2><%= t('.title', :forum => forum) %></h2>

<h3><%= t('posts_count', :count => @posts.count, :scope => 'forem.general') %></h3>

<%= form_tag forem.forum_moderate_posts_url(forum), :method => :put do %>
  <div id='posts'>
    <% @posts.limit(25).group_by(&:topic).each do |topic, posts| %>
      <h4><%= forem_emojify(topic.forum.title) %> &raquo; <%= forem_emojify(topic.subject) %></h4>
      <%= render posts, :mass_moderation => true %>
    <% end %>
  </div>
  <%= submit_tag "Moderate", :class => "btn btn-primary" %>
<% end %>

app/views/forem/posts/_form.html.erb
<%= f.input :text %>

<% if params[:reply_to_id] %>
  <%= f.hidden_field :reply_to_id, :value => params[:reply_to_id] %>
<% end %>

app/views/forem/posts/_moderation_tools.html.erb
<%= fields_for "posts[#{post.id}]" do |f| %>
  <%= render "/forem/moderation/options", :f => f %>
<% end %>
<br>

app/views/forem/posts/_post.html.erb
<a name='post-<%= post.id %>'></a>
<div class="row">
  <div id='post_<%= post_counter + 1 %>' class='post <%= cycle('odd', 'even') -%> span10'>
      <% if post.pending_review? %>
      <div class='moderation alert'>
        <%= t(".pending_review") %>
        <% if forem_admin_or_moderator?(post.topic.forum) %>
          <% if local_assigns[:mass_moderation] %>
            <%= render "/forem/posts/moderation_tools", :post => post %>
          <% else %>
            <%= form_tag forem.forum_moderate_posts_path(post.topic.forum), :method => :put do %>
              <%= render "/forem/posts/moderation_tools", :post => post %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <div class='user span2'>
      <div class='username'>
        <%= link_to_if Forem.user_profile_links, post.user, [main_app, post.user] %>
      </div>
      <div class='icon'><%= forem_avatar(post.user, :size => 60) %></div>
    </div>

    <div class='contents span7'>
      <a href='#post-<%= post.id %>'>
        <time datetime="<%= post.created_at.to_s(:db) -%>"><%= "#{time_ago_in_words(post.created_at)} #{t("ago")}" %></time>
      </a>
      <%= forem_format(post.text) %>

      <% if post.reply_to %>
        <div class='in-reply-to'>
          <%= link_to "#{t("forem.post.in_reply_to")} #{post.reply_to.user}", "#post-#{post.reply_to.id}" %>
        </div>
      <% end %>

      <% if forem_user %>
        <div class='btn-group'>
          <% if can?(:reply, post.topic) %>
            <% if post.topic.can_be_replied_to? %>
              <%= link_to t('reply', :scope => 'forem.topic'), forem.new_topic_post_path(post.topic, :reply_to_id => post.id), :class => "btn btn-primary" %>
              <%= link_to t('quote', :scope => 'forem.topic'), forem.new_topic_post_path(post.topic, :reply_to_id => post.id, :quote => true), :class => "btn btn-success" %>
            <% end %>
          <% end %>
          <% if post.owner_or_admin?(forem_user) %>
            <% if can?(:edit_post, post.topic.forum) %>
              <%= link_to t('edit', :scope => 'forem.post'), forem.edit_topic_post_path(post.topic, post), :class => "btn btn-info" %>
            <% end %>
            <%= link_to t('delete', :scope => 'forem.topic'), forem.topic_post_path(post.topic, post), :method => :delete, data: { :confirm => t("are_you_sure") }, :class => "btn btn-danger" %>
          <% end %>
        </div>
      <% end %>
    
    </div>
  </div>
</div>

app/views/forem/posts/_reply_to_post.html.erb
<a name='post-<%= post.id %>'></a>
<div id='post_<%= post.id %>' class='reply_to_post post <%= cycle('odd', 'even') -%> span10'>
  <div class='user span2'>
    <div class='username'>
      <%= link_to_if Forem.user_profile_links, post.user, [main_app, post.user] %>
    </div>
    <div class='icon'><%= forem_avatar(post.user, :size => 60) %></div>
  </div>

  <div class='contents span7'>
    <time datetime="<%= post.created_at.to_s(:db) -%>"><%= "#{time_ago_in_words(post.created_at)} #{t("ago")}" %></time>
    <%= forem_format(post.text) %>

    <% if post.reply_to %>
      <span class='in_reply_to'>
        <%= link_to "#{t("forem.post.in_reply_to")} #{post.reply_to.user}", "#post-#{post.reply_to.id}" %>
      </span>
    <% end %>
  </div>
</div>

app/views/forem/posts/edit.html.erb
<%= render :partial => 'forem/forums/head', :locals => { :forum => @topic.forum } %>

<h2><%= t("forem.post.edit") %></h2>

<%= simple_form_for [forem, @topic, @post] do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= f.submit t("forem.post.buttons.edit") %>
<% end %>

app/views/forem/posts/new.html.erb
<%= render :partial => 'forem/forums/head', :locals => { :forum => @topic.forum } %>

<h2><%= t("forem.post.new") %></h2>

<% if @reply_to_post %>
  <div class='row'>
    <%= render 'reply_to_post', :post => @reply_to_post %>
  </div>
<% else %>
  <h3 class='topic_subject'>
    <%= @topic.subject %>
  </h3>
<% end %>

<%= simple_form_for [forem, @topic, @post] do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= f.submit t("forem.post.buttons.reply"), :class => "btn btn-primary" %>
<% end %>

app/views/forem/topics/_form.html.erb
<%= simple_form_for [forem, @forum, @topic] do |f| %>
  <%= f.input :subject %>

  <%= f.simple_fields_for :posts do |post| %>
    <%= render :partial => "forem/posts/form", :locals => { :f => post }%>
  <% end %>
  
  <%= f.submit :class => "btn btn-primary" %>
<% end %>
`

app/views/forem/topics/_head.html.erb
<h2><%= link_to t('forem.forum.forums'), forem.forums_path %> &raquo; <%= link_to forem_emojify(topic.forum.title), [forem, topic.forum] %> &raquo; <%= forem_emojify(topic.subject) %></h2>

app/views/forem/topics/_topic.html.erb
<tr class="topic <%= cycle('odd', 'even') %> <%= topic.locked? ? 'locked' : 'unlocked' %>">
  <td class='icon'>
    <% if topic.locked? %>
      <span class='lock icon'></span>
    <% end %>
    <% if topic.pinned? %>
      <span class='pin icon'></span>
    <% end %>
    <% if forem_user && view = topic.view_for(forem_user) %>
      <% if topic.posts.exists?(["created_at > ?", view.updated_at]) %>
        <span class='new_posts icon'>new</span>
      <% end %>
    <% end %>
  </td>
  <td class='byline'>
    <%= new_since_last_view_text(topic) %>
    <div class='subject'><%= link_to forem_emojify(topic.subject), forem.forum_topic_path(@forum, topic) %></div>
    <div class='started-by'><%= t "started_by" %><%= relevant_posts(topic).first.user %></div>
  </td>
  <td class='latest-post text-center'>
    <%= link_to_latest_post(topic) -%>
  </td>
  <td class='posts-count text-center'><%= relevant_posts(topic).count %></td>
  <td class='views-count text-center'><%= topic.views_count %></td>
</tr>

app/views/forem/topics/new.html.erb
<%= render :partial => 'forem/forums/head', :locals => { :forum => @topic.forum } %>

<h2><%= t("forem.topic.new") %></h2>

<%= render "form" %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

  <h2><%= post.title %></h2>
  <p><%= post.body %></p>
  <p><%= link_to 'Read more..', post %></p>
  <% if user_signed_in? %>
    <p><%= link_to 'Edit', edit_post_path(post) %></p>
    <p><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>

<% end %>

<% if user_signed_in? %>
  <p><%= link_to 'New Post', new_post_path %></p>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @post.title %></h1>

<p><%= @post.body %></p>

<% if user_signed_in? %>
  <%= form_for [@post, Comment.new] do |f| %>
    <%= f.label :body, "New Comment"  %> <br />
    <%= f.text_area :body %> <br />
    <%= f.submit "Add Comment" %>
  <% end %>
<% else %>
  <h2>Want to comment? <%= link_to "Login", new_user_session_path %> or <%= link_to "sign up", new_user_registration_path %></h2>
<% end %>

<div class="comments">
  <%= render :partial => @post.comments %>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>